### ISSUE TITLE
subprocess.CalledProcessError: Command '['which', 'c++']' returned non-zero exit status 1

### ISSUE THREAD

**Issue by koncle** [tamakoji/pytorch-syncbn#7]
I follow the installation in readme.md. But still got a problem when running the `test.py` file.
My torch version is 1.1.0, cudnn is 7.6.0, on ubuntu18.04.

```
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    from modules import nn as NN
  File "/data/zj/pytorch-syncbn/modules/nn/__init__.py", line 1, in <module>
    from .syncbn import *
  File "/data/zj/pytorch-syncbn/modules/nn/syncbn.py", line 23, in <module>
    from modules.functional import batchnorm2d_sync
  File "/data/zj/pytorch-syncbn/modules/functional/__init__.py", line 1, in <module>
    from .syncbn import batchnorm2d_sync
  File "/data/zj/pytorch-syncbn/modules/functional/syncbn.py", line 17, in <module>
    from ._csrc import _backend
  File "/data/zj/pytorch-syncbn/modules/functional/_csrc.py", line 54, in <module>
    _backend = _load_C_extensions()
  File "/data/zj/pytorch-syncbn/modules/functional/_csrc.py", line 50, in _load_C_extensions
    extra_cuda_cflags=extra_cuda_cflags,
  File "/usr/local/anaconda3/envs/sharedEnv/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 644, in load
    is_python_module)
  File "/usr/local/anaconda3/envs/sharedEnv/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 813, in _jit_compile
    with_cuda=with_cuda)
  File "/usr/local/anaconda3/envs/sharedEnv/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 841, in _write_ninja_file_and_build
    check_compiler_abi_compatibility(compiler)
  File "/usr/local/anaconda3/envs/sharedEnv/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 162, in check_compiler_abi_compatibility
    if not check_compiler_ok_for_platform(compiler):
  File "/usr/local/anaconda3/envs/sharedEnv/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 138, in check_compiler_ok_for_platform
    which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
  File "/usr/local/anaconda3/envs/sharedEnv/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/local/anaconda3/envs/sharedEnv/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['which', 'c++']' returned non-zero exit status 1.
```

**Comment by yosagaf** [comment]
Lookin for an answer, I have the same issue.

**Comment by shiyuetianqiang** [comment]
Maybe you need install python-dev
